const mongoose = require('mongoose');

const payrollSchema = new mongoose.Schema(
    {
        employee: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Employee',
            required: true,
        },
        user: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
        },
        month: {
            type: Number,
            required: true,
            min: 1,
            max: 12,
        },
        year: {
            type: Number,
            required: true,
        },
        // Salary Components
        basicSalary: {
            type: Number,
            required: [true, 'Basic salary is required'],
            min: 0,
        },
        hra: {
            // House Rent Allowance
            type: Number,
            default: 0,
        },
        transportAllowance: {
            type: Number,
            default: 0,
        },
        medicalAllowance: {
            type: Number,
            default: 0,
        },
        specialAllowance: {
            type: Number,
            default: 0,
        },
        otherAllowances: {
            type: Number,
            default: 0,
        },
        // Deductions
        providentFund: {
            type: Number,
            default: 0,
        },
        professionalTax: {
            type: Number,
            default: 0,
        },
        incomeTax: {
            type: Number,
            default: 0,
        },
        otherDeductions: {
            type: Number,
            default: 0,
        },
        // Attendance based
        daysWorked: {
            type: Number,
            default: 0,
        },
        totalWorkingDays: {
            type: Number,
            default: 0,
        },
        leavesDeducted: {
            type: Number,
            default: 0,
        },
        // Calculated fields
        grossSalary: {
            type: Number,
            default: 0,
        },
        totalDeductions: {
            type: Number,
            default: 0,
        },
        netSalary: {
            type: Number,
            default: 0,
        },
        // Payment details
        paymentStatus: {
            type: String,
            enum: ['Pending', 'Processed', 'Paid', 'On Hold'],
            default: 'Pending',
        },
        paymentDate: Date,
        paymentMethod: {
            type: String,
            enum: ['Bank Transfer', 'Cheque', 'Cash', 'UPI'],
        },
        transactionId: String,
        remarks: String,
        // Generated by
        generatedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
    },
    {
        timestamps: true,
    }
);

// Calculate gross, deductions, and net salary before saving
payrollSchema.pre('save', function (next) {
    // Calculate gross salary
    this.grossSalary =
        this.basicSalary +
        this.hra +
        this.transportAllowance +
        this.medicalAllowance +
        this.specialAllowance +
        this.otherAllowances;

    // Calculate total deductions
    this.totalDeductions =
        this.providentFund +
        this.professionalTax +
        this.incomeTax +
        this.otherDeductions;

    // Calculate net salary
    this.netSalary = this.grossSalary - this.totalDeductions;

    // Adjust for days worked if less than total working days
    if (this.totalWorkingDays > 0 && this.daysWorked < this.totalWorkingDays) {
        const perDaySalary = this.netSalary / this.totalWorkingDays;
        this.netSalary = perDaySalary * this.daysWorked;
    }

    next();
});

// Compound index to ensure one payroll record per employee per month
payrollSchema.index({ employee: 1, month: 1, year: 1 }, { unique: true });
payrollSchema.index({ user: 1, year: -1, month: -1 });
payrollSchema.index({ paymentStatus: 1 });

// Static method to get annual salary
payrollSchema.statics.getAnnualSalary = async function (employeeId, year) {
    const result = await this.aggregate([
        {
            $match: {
                employee: mongoose.Types.ObjectId(employeeId),
                year: year,
                paymentStatus: 'Paid',
            },
        },
        {
            $group: {
                _id: null,
                totalGross: { $sum: '$grossSalary' },
                totalDeductions: { $sum: '$totalDeductions' },
                totalNet: { $sum: '$netSalary' },
            },
        },
    ]);

    return result[0] || { totalGross: 0, totalDeductions: 0, totalNet: 0 };
};

const Payroll = mongoose.model('Payroll', payrollSchema);

module.exports = Payroll;
